apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: j4zlv8ldm-nodejs 
  janus-idp.io/tekton: j4zlv8ldm-nodejs
  backstage.io/kubernetes-id: j4zlv8ldm-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: j4zlv8ldm-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml